// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// `AuthzExtension` is a resource that allows traffic forwarding
/// to a callout backend service to make an authorization decision.
public struct AuthzExtension: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Identifier. Name of the `AuthzExtension` resource in the
  /// following format:
  /// `projects/{project}/locations/{location}/authzExtensions/{authz_extension}`.
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp when the resource was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The timestamp when the resource was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. A human-readable description of the resource.
  public var description: Swift.String = Swift.String()

  /// Optional. Set of labels associated with the `AuthzExtension`
  /// resource.
  ///
  /// The format must comply with [the requirements for
  /// labels](/compute/docs/labeling-resources#requirements) for Google Cloud
  /// resources.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. All backend services and forwarding rules referenced by this
  /// extension must share the same load balancing scheme. Supported values:
  /// `INTERNAL_MANAGED`, `EXTERNAL_MANAGED`. Can be omitted for AuthzExtensions
  /// that do not reference a backend service. For more information, refer to
  /// [Backend services
  /// overview](https://cloud.google.com/load-balancing/docs/backend-service).
  public var loadBalancingScheme: LoadBalancingScheme = LoadBalancingScheme()

  /// Optional. The `:authority` header in the gRPC request sent from Envoy to
  /// the extension service. It is required when the `service` field points to a
  /// backend service or a wasm plugin.
  public var authority: Swift.String = Swift.String()

  /// Required. The reference to the service that runs the extension.
  ///
  /// To configure a callout extension, `service` must be a fully-qualified
  /// reference
  /// to a [backend
  /// service](https://cloud.google.com/compute/docs/reference/rest/v1/backendServices)
  /// in the format:
  /// `https://www.googleapis.com/compute/v1/projects/{project}/regions/{region}/backendServices/{backendService}`
  /// or
  /// `https://www.googleapis.com/compute/v1/projects/{project}/global/backendServices/{backendService}`.
  public var service: Swift.String = Swift.String()

  /// Required. Specifies the timeout for each individual message on the stream.
  /// The timeout must be between 10-10000 milliseconds.
  public var timeout: GoogleCloudWKT.Duration? = nil

  /// Optional. Determines how the proxy behaves if the call to the extension
  /// fails or times out.
  ///
  /// When set to `TRUE`, request or response processing continues without
  /// error. Any subsequent extensions in the extension chain are also
  /// executed. When set to `FALSE` or the default setting of `FALSE` is used,
  /// one of the following happens:
  ///
  /// * If response headers have not been delivered to the downstream client,
  /// a generic 500 error is returned to the client. The error response can be
  /// tailored by configuring a custom error response in the load balancer.
  ///
  /// * If response headers have been delivered, then the HTTP stream to the
  /// downstream client is reset.
  public var failOpen: Swift.Bool = Swift.Bool()

  /// Optional. The metadata provided here is included as part of the
  /// `metadata_context` (of type `google.protobuf.Struct`) in the
  /// `ProcessingRequest` message sent to the extension
  /// server. The metadata is available under the namespace
  /// `com.google.authz_extension.<resource_name>`.
  /// The following variables are supported in the metadata Struct:
  ///
  /// `{forwarding_rule_id}` - substituted with the forwarding rule's fully
  ///   qualified resource name.
  public var metadata: GoogleCloudWKT.Struct? = nil

  /// Optional. List of the HTTP headers to forward to the extension
  /// (from the client). If omitted, all headers are sent.
  /// Each element is a string indicating the header name.
  public var forwardHeaders: [Swift.String] = []

  /// Optional. List of the Envoy attributes to forward to the extension server.
  /// The attributes provided here are included as part of the
  /// `ProcessingRequest.attributes` field (of type
  /// `map<string, google.protobuf.Struct>`), where the keys are the attribute
  /// names. Refer to the
  /// [documentation](https://cloud.google.com/service-extensions/docs/cel-matcher-language-reference#attributes)
  /// for the names of attributes that can be forwarded. If omitted, no
  /// attributes are sent. Each element is a string indicating the
  /// attribute name.
  public var forwardAttributes: [Swift.String] = []

  /// Optional. The format of communication supported by the callout extension.
  /// This field is supported only for regional `AuthzExtension` resources. If
  /// not specified, the default value `EXT_PROC_GRPC` is used. Global
  /// `AuthzExtension` resources use the `EXT_PROC_GRPC` wire format.
  public var wireFormat: WireFormat = WireFormat()

  /// Initialize a new instance of `AuthzExtension`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuthzExtension().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkservices.v1.AuthzExtension"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
