// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service describing handlers for resources.
///
/// @Snippet(path: "DepServiceQuickstart")
public final class DepServiceClient: Clients.DepServiceProtocol, Sendable {
  let inner: any Clients.DepServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `DepServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.DepServiceStub = try Clients.DepServiceTransport(options)
    inner = Clients.DepServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DepServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists `LbTrafficExtension` resources in a given project and location.
  ///
  /// @Snippet(path: "DepService_ListLbTrafficExtensions")
  public func listLbTrafficExtensions(
    request: ListLbTrafficExtensionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.ListLbTrafficExtensionsResponse {
    try await self.inner.listLbTrafficExtensions(request: request, options: options)
  }

  /// Gets details of the specified `LbTrafficExtension` resource.
  ///
  /// @Snippet(path: "DepService_GetLbTrafficExtension")
  public func getLbTrafficExtension(
    request: GetLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.LbTrafficExtension {
    try await self.inner.getLbTrafficExtension(request: request, options: options)
  }

  /// Creates a new `LbTrafficExtension` resource in a given project and
  /// location.
  ///
  /// @Snippet(path: "DepService_CreateLbTrafficExtension")
  public func createLbTrafficExtension(
    request: CreateLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createLbTrafficExtension(request: request, options: options)
  }

  /// Creates a new `LbTrafficExtension` resource in a given project and
  /// location.
  ///
  /// @Snippet(path: "DepService_CreateLbTrafficExtension")
  public func createLbTrafficExtensionPollingUntilDone(
    request: CreateLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LbTrafficExtension> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<LbTrafficExtension>.State in
      return try op._extractStatus(LbTrafficExtension.self)
    }
    let rawOp = try await self.createLbTrafficExtension(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<LbTrafficExtension>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of the specified `LbTrafficExtension` resource.
  ///
  /// @Snippet(path: "DepService_UpdateLbTrafficExtension")
  public func updateLbTrafficExtension(
    request: UpdateLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateLbTrafficExtension(request: request, options: options)
  }

  /// Updates the parameters of the specified `LbTrafficExtension` resource.
  ///
  /// @Snippet(path: "DepService_UpdateLbTrafficExtension")
  public func updateLbTrafficExtensionPollingUntilDone(
    request: UpdateLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LbTrafficExtension> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<LbTrafficExtension>.State in
      return try op._extractStatus(LbTrafficExtension.self)
    }
    let rawOp = try await self.updateLbTrafficExtension(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<LbTrafficExtension>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified `LbTrafficExtension` resource.
  ///
  /// @Snippet(path: "DepService_DeleteLbTrafficExtension")
  public func deleteLbTrafficExtension(
    request: DeleteLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteLbTrafficExtension(request: request, options: options)
  }

  /// Deletes the specified `LbTrafficExtension` resource.
  ///
  /// @Snippet(path: "DepService_DeleteLbTrafficExtension")
  public func deleteLbTrafficExtensionPollingUntilDone(
    request: DeleteLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteLbTrafficExtension(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists `LbRouteExtension` resources in a given project and location.
  ///
  /// @Snippet(path: "DepService_ListLbRouteExtensions")
  public func listLbRouteExtensions(
    request: ListLbRouteExtensionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.ListLbRouteExtensionsResponse {
    try await self.inner.listLbRouteExtensions(request: request, options: options)
  }

  /// Gets details of the specified `LbRouteExtension` resource.
  ///
  /// @Snippet(path: "DepService_GetLbRouteExtension")
  public func getLbRouteExtension(
    request: GetLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.LbRouteExtension {
    try await self.inner.getLbRouteExtension(request: request, options: options)
  }

  /// Creates a new `LbRouteExtension` resource in a given project and location.
  ///
  /// @Snippet(path: "DepService_CreateLbRouteExtension")
  public func createLbRouteExtension(
    request: CreateLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createLbRouteExtension(request: request, options: options)
  }

  /// Creates a new `LbRouteExtension` resource in a given project and location.
  ///
  /// @Snippet(path: "DepService_CreateLbRouteExtension")
  public func createLbRouteExtensionPollingUntilDone(
    request: CreateLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LbRouteExtension> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<LbRouteExtension>.State in
      return try op._extractStatus(LbRouteExtension.self)
    }
    let rawOp = try await self.createLbRouteExtension(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<LbRouteExtension>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of the specified `LbRouteExtension` resource.
  ///
  /// @Snippet(path: "DepService_UpdateLbRouteExtension")
  public func updateLbRouteExtension(
    request: UpdateLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateLbRouteExtension(request: request, options: options)
  }

  /// Updates the parameters of the specified `LbRouteExtension` resource.
  ///
  /// @Snippet(path: "DepService_UpdateLbRouteExtension")
  public func updateLbRouteExtensionPollingUntilDone(
    request: UpdateLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LbRouteExtension> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<LbRouteExtension>.State in
      return try op._extractStatus(LbRouteExtension.self)
    }
    let rawOp = try await self.updateLbRouteExtension(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<LbRouteExtension>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified `LbRouteExtension` resource.
  ///
  /// @Snippet(path: "DepService_DeleteLbRouteExtension")
  public func deleteLbRouteExtension(
    request: DeleteLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteLbRouteExtension(request: request, options: options)
  }

  /// Deletes the specified `LbRouteExtension` resource.
  ///
  /// @Snippet(path: "DepService_DeleteLbRouteExtension")
  public func deleteLbRouteExtensionPollingUntilDone(
    request: DeleteLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteLbRouteExtension(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists `LbEdgeExtension` resources in a given project and location.
  ///
  /// @Snippet(path: "DepService_ListLbEdgeExtensions")
  public func listLbEdgeExtensions(
    request: ListLbEdgeExtensionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.ListLbEdgeExtensionsResponse {
    try await self.inner.listLbEdgeExtensions(request: request, options: options)
  }

  /// Gets details of the specified `LbEdgeExtension` resource.
  ///
  /// @Snippet(path: "DepService_GetLbEdgeExtension")
  public func getLbEdgeExtension(
    request: GetLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.LbEdgeExtension {
    try await self.inner.getLbEdgeExtension(request: request, options: options)
  }

  /// Creates a new `LbEdgeExtension` resource in a given project and location.
  ///
  /// @Snippet(path: "DepService_CreateLbEdgeExtension")
  public func createLbEdgeExtension(
    request: CreateLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createLbEdgeExtension(request: request, options: options)
  }

  /// Creates a new `LbEdgeExtension` resource in a given project and location.
  ///
  /// @Snippet(path: "DepService_CreateLbEdgeExtension")
  public func createLbEdgeExtensionPollingUntilDone(
    request: CreateLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LbEdgeExtension> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<LbEdgeExtension>.State in
      return try op._extractStatus(LbEdgeExtension.self)
    }
    let rawOp = try await self.createLbEdgeExtension(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<LbEdgeExtension>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of the specified `LbEdgeExtension` resource.
  ///
  /// @Snippet(path: "DepService_UpdateLbEdgeExtension")
  public func updateLbEdgeExtension(
    request: UpdateLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateLbEdgeExtension(request: request, options: options)
  }

  /// Updates the parameters of the specified `LbEdgeExtension` resource.
  ///
  /// @Snippet(path: "DepService_UpdateLbEdgeExtension")
  public func updateLbEdgeExtensionPollingUntilDone(
    request: UpdateLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LbEdgeExtension> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<LbEdgeExtension>.State in
      return try op._extractStatus(LbEdgeExtension.self)
    }
    let rawOp = try await self.updateLbEdgeExtension(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<LbEdgeExtension>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified `LbEdgeExtension` resource.
  ///
  /// @Snippet(path: "DepService_DeleteLbEdgeExtension")
  public func deleteLbEdgeExtension(
    request: DeleteLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteLbEdgeExtension(request: request, options: options)
  }

  /// Deletes the specified `LbEdgeExtension` resource.
  ///
  /// @Snippet(path: "DepService_DeleteLbEdgeExtension")
  public func deleteLbEdgeExtensionPollingUntilDone(
    request: DeleteLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteLbEdgeExtension(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists `AuthzExtension` resources in a given project and location.
  ///
  /// @Snippet(path: "DepService_ListAuthzExtensions")
  public func listAuthzExtensions(
    request: ListAuthzExtensionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.ListAuthzExtensionsResponse {
    try await self.inner.listAuthzExtensions(request: request, options: options)
  }

  /// Gets details of the specified `AuthzExtension` resource.
  ///
  /// @Snippet(path: "DepService_GetAuthzExtension")
  public func getAuthzExtension(
    request: GetAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.AuthzExtension {
    try await self.inner.getAuthzExtension(request: request, options: options)
  }

  /// Creates a new `AuthzExtension` resource in a given project
  /// and location.
  ///
  /// @Snippet(path: "DepService_CreateAuthzExtension")
  public func createAuthzExtension(
    request: CreateAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAuthzExtension(request: request, options: options)
  }

  /// Creates a new `AuthzExtension` resource in a given project
  /// and location.
  ///
  /// @Snippet(path: "DepService_CreateAuthzExtension")
  public func createAuthzExtensionPollingUntilDone(
    request: CreateAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AuthzExtension> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AuthzExtension>.State in
      return try op._extractStatus(AuthzExtension.self)
    }
    let rawOp = try await self.createAuthzExtension(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AuthzExtension>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of the specified `AuthzExtension`
  /// resource.
  ///
  /// @Snippet(path: "DepService_UpdateAuthzExtension")
  public func updateAuthzExtension(
    request: UpdateAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAuthzExtension(request: request, options: options)
  }

  /// Updates the parameters of the specified `AuthzExtension`
  /// resource.
  ///
  /// @Snippet(path: "DepService_UpdateAuthzExtension")
  public func updateAuthzExtensionPollingUntilDone(
    request: UpdateAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AuthzExtension> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AuthzExtension>.State in
      return try op._extractStatus(AuthzExtension.self)
    }
    let rawOp = try await self.updateAuthzExtension(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AuthzExtension>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified `AuthzExtension` resource.
  ///
  /// @Snippet(path: "DepService_DeleteAuthzExtension")
  public func deleteAuthzExtension(
    request: DeleteAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAuthzExtension(request: request, options: options)
  }

  /// Deletes the specified `AuthzExtension` resource.
  ///
  /// @Snippet(path: "DepService_DeleteAuthzExtension")
  public func deleteAuthzExtensionPollingUntilDone(
    request: DeleteAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAuthzExtension(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "DepService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "DepService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "DepService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "DepService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "DepService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DepService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DepService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DepService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DepService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DepServiceClient`.
  ///
  /// To mock `DepServiceClient` change your functions to receive
  /// `some DepServiceProtocol` or `any DepServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DepServiceProtocol: Sendable {
    /// See `DepServiceClient.createLbTrafficExtension`.
    func createLbTrafficExtensionPollingUntilDone(request: CreateLbTrafficExtensionRequest)
      async throws -> any GoogleGax.PollableOperation<LbTrafficExtension>

    /// See `DepServiceClient.createLbTrafficExtension`.
    func createLbTrafficExtensionPollingUntilDone(
      parent: Swift.String,
      lbTrafficExtension: LbTrafficExtension?,
      lbTrafficExtensionId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<LbTrafficExtension>

    /// See `DepServiceClient.updateLbTrafficExtension`.
    func updateLbTrafficExtensionPollingUntilDone(request: UpdateLbTrafficExtensionRequest)
      async throws -> any GoogleGax.PollableOperation<LbTrafficExtension>

    /// See `DepServiceClient.updateLbTrafficExtension`.
    func updateLbTrafficExtensionPollingUntilDone(
      lbTrafficExtension: LbTrafficExtension?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<LbTrafficExtension>

    /// See `DepServiceClient.deleteLbTrafficExtension`.
    func deleteLbTrafficExtensionPollingUntilDone(request: DeleteLbTrafficExtensionRequest)
      async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DepServiceClient.deleteLbTrafficExtension`.
    func deleteLbTrafficExtensionPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DepServiceClient.createLbRouteExtension`.
    func createLbRouteExtensionPollingUntilDone(request: CreateLbRouteExtensionRequest) async throws
      -> any GoogleGax.PollableOperation<LbRouteExtension>

    /// See `DepServiceClient.createLbRouteExtension`.
    func createLbRouteExtensionPollingUntilDone(
      parent: Swift.String,
      lbRouteExtension: LbRouteExtension?,
      lbRouteExtensionId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<LbRouteExtension>

    /// See `DepServiceClient.updateLbRouteExtension`.
    func updateLbRouteExtensionPollingUntilDone(request: UpdateLbRouteExtensionRequest) async throws
      -> any GoogleGax.PollableOperation<LbRouteExtension>

    /// See `DepServiceClient.updateLbRouteExtension`.
    func updateLbRouteExtensionPollingUntilDone(
      lbRouteExtension: LbRouteExtension?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<LbRouteExtension>

    /// See `DepServiceClient.deleteLbRouteExtension`.
    func deleteLbRouteExtensionPollingUntilDone(request: DeleteLbRouteExtensionRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DepServiceClient.deleteLbRouteExtension`.
    func deleteLbRouteExtensionPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DepServiceClient.createLbEdgeExtension`.
    func createLbEdgeExtensionPollingUntilDone(request: CreateLbEdgeExtensionRequest) async throws
      -> any GoogleGax.PollableOperation<LbEdgeExtension>

    /// See `DepServiceClient.createLbEdgeExtension`.
    func createLbEdgeExtensionPollingUntilDone(
      parent: Swift.String,
      lbEdgeExtension: LbEdgeExtension?,
      lbEdgeExtensionId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<LbEdgeExtension>

    /// See `DepServiceClient.updateLbEdgeExtension`.
    func updateLbEdgeExtensionPollingUntilDone(request: UpdateLbEdgeExtensionRequest) async throws
      -> any GoogleGax.PollableOperation<LbEdgeExtension>

    /// See `DepServiceClient.updateLbEdgeExtension`.
    func updateLbEdgeExtensionPollingUntilDone(
      lbEdgeExtension: LbEdgeExtension?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<LbEdgeExtension>

    /// See `DepServiceClient.deleteLbEdgeExtension`.
    func deleteLbEdgeExtensionPollingUntilDone(request: DeleteLbEdgeExtensionRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DepServiceClient.deleteLbEdgeExtension`.
    func deleteLbEdgeExtensionPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DepServiceClient.createAuthzExtension`.
    func createAuthzExtensionPollingUntilDone(request: CreateAuthzExtensionRequest) async throws
      -> any GoogleGax.PollableOperation<AuthzExtension>

    /// See `DepServiceClient.createAuthzExtension`.
    func createAuthzExtensionPollingUntilDone(
      parent: Swift.String,
      authzExtension: AuthzExtension?,
      authzExtensionId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<AuthzExtension>

    /// See `DepServiceClient.updateAuthzExtension`.
    func updateAuthzExtensionPollingUntilDone(request: UpdateAuthzExtensionRequest) async throws
      -> any GoogleGax.PollableOperation<AuthzExtension>

    /// See `DepServiceClient.updateAuthzExtension`.
    func updateAuthzExtensionPollingUntilDone(
      authzExtension: AuthzExtension?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<AuthzExtension>

    /// See `DepServiceClient.deleteAuthzExtension`.
    func deleteAuthzExtensionPollingUntilDone(request: DeleteAuthzExtensionRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DepServiceClient.deleteAuthzExtension`.
    func deleteAuthzExtensionPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DepServiceClient.listLbTrafficExtensions`.
    func listLbTrafficExtensions(
      request: ListLbTrafficExtensionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListLbTrafficExtensionsResponse

    /// See `DepServiceClient.getLbTrafficExtension`.
    func getLbTrafficExtension(
      request: GetLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.LbTrafficExtension

    /// See `DepServiceClient.createLbTrafficExtension`.
    func createLbTrafficExtension(
      request: CreateLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DepServiceClient.createLbTrafficExtension`.
    func createLbTrafficExtensionPollingUntilDone(
      request: CreateLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<LbTrafficExtension>

    /// See `DepServiceClient.updateLbTrafficExtension`.
    func updateLbTrafficExtension(
      request: UpdateLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DepServiceClient.updateLbTrafficExtension`.
    func updateLbTrafficExtensionPollingUntilDone(
      request: UpdateLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<LbTrafficExtension>

    /// See `DepServiceClient.deleteLbTrafficExtension`.
    func deleteLbTrafficExtension(
      request: DeleteLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DepServiceClient.deleteLbTrafficExtension`.
    func deleteLbTrafficExtensionPollingUntilDone(
      request: DeleteLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DepServiceClient.listLbRouteExtensions`.
    func listLbRouteExtensions(
      request: ListLbRouteExtensionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListLbRouteExtensionsResponse

    /// See `DepServiceClient.getLbRouteExtension`.
    func getLbRouteExtension(
      request: GetLbRouteExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.LbRouteExtension

    /// See `DepServiceClient.createLbRouteExtension`.
    func createLbRouteExtension(
      request: CreateLbRouteExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DepServiceClient.createLbRouteExtension`.
    func createLbRouteExtensionPollingUntilDone(
      request: CreateLbRouteExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<LbRouteExtension>

    /// See `DepServiceClient.updateLbRouteExtension`.
    func updateLbRouteExtension(
      request: UpdateLbRouteExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DepServiceClient.updateLbRouteExtension`.
    func updateLbRouteExtensionPollingUntilDone(
      request: UpdateLbRouteExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<LbRouteExtension>

    /// See `DepServiceClient.deleteLbRouteExtension`.
    func deleteLbRouteExtension(
      request: DeleteLbRouteExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DepServiceClient.deleteLbRouteExtension`.
    func deleteLbRouteExtensionPollingUntilDone(
      request: DeleteLbRouteExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DepServiceClient.listLbEdgeExtensions`.
    func listLbEdgeExtensions(
      request: ListLbEdgeExtensionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListLbEdgeExtensionsResponse

    /// See `DepServiceClient.getLbEdgeExtension`.
    func getLbEdgeExtension(
      request: GetLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.LbEdgeExtension

    /// See `DepServiceClient.createLbEdgeExtension`.
    func createLbEdgeExtension(
      request: CreateLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DepServiceClient.createLbEdgeExtension`.
    func createLbEdgeExtensionPollingUntilDone(
      request: CreateLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<LbEdgeExtension>

    /// See `DepServiceClient.updateLbEdgeExtension`.
    func updateLbEdgeExtension(
      request: UpdateLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DepServiceClient.updateLbEdgeExtension`.
    func updateLbEdgeExtensionPollingUntilDone(
      request: UpdateLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<LbEdgeExtension>

    /// See `DepServiceClient.deleteLbEdgeExtension`.
    func deleteLbEdgeExtension(
      request: DeleteLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DepServiceClient.deleteLbEdgeExtension`.
    func deleteLbEdgeExtensionPollingUntilDone(
      request: DeleteLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DepServiceClient.listAuthzExtensions`.
    func listAuthzExtensions(
      request: ListAuthzExtensionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListAuthzExtensionsResponse

    /// See `DepServiceClient.getAuthzExtension`.
    func getAuthzExtension(
      request: GetAuthzExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.AuthzExtension

    /// See `DepServiceClient.createAuthzExtension`.
    func createAuthzExtension(
      request: CreateAuthzExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DepServiceClient.createAuthzExtension`.
    func createAuthzExtensionPollingUntilDone(
      request: CreateAuthzExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AuthzExtension>

    /// See `DepServiceClient.updateAuthzExtension`.
    func updateAuthzExtension(
      request: UpdateAuthzExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DepServiceClient.updateAuthzExtension`.
    func updateAuthzExtensionPollingUntilDone(
      request: UpdateAuthzExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AuthzExtension>

    /// See `DepServiceClient.deleteAuthzExtension`.
    func deleteAuthzExtension(
      request: DeleteAuthzExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DepServiceClient.deleteAuthzExtension`.
    func deleteAuthzExtensionPollingUntilDone(
      request: DeleteAuthzExtensionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DepServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `DepServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `DepServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `DepServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `DepServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `DepServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `DepServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `DepServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.DepServiceProtocol {
  public func listLbTrafficExtensions(request: ListLbTrafficExtensionsRequest) async throws
    -> GoogleCloudNetworkServicesV1.ListLbTrafficExtensionsResponse
  {
    try await self.listLbTrafficExtensions(request: request, options: .init())
  }

  public func listLbTrafficExtensions(
    request: ListLbTrafficExtensionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.ListLbTrafficExtensionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLbTrafficExtensionsByItems(
    request: ListLbTrafficExtensionsRequest
  ) -> any AsyncSequence<LbTrafficExtension, Swift.Error> {
    self.listLbTrafficExtensionsByItems(request: request, options: .init())
  }

  /// Lists `LbTrafficExtension` resources in a given project and location.
  ///
  /// @Snippet(path: "DepService_ListLbTrafficExtensions")
  public func listLbTrafficExtensionsByItems(
    request: ListLbTrafficExtensionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<LbTrafficExtension, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudNetworkServicesV1.ListLbTrafficExtensionsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLbTrafficExtensions(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLbTrafficExtensionsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<LbTrafficExtension, Swift.Error> {
    let request = ListLbTrafficExtensionsRequest().with {
      $0.parent = parent
    }
    return self.listLbTrafficExtensionsByItems(request: request)
  }

  public func getLbTrafficExtension(request: GetLbTrafficExtensionRequest) async throws
    -> GoogleCloudNetworkServicesV1.LbTrafficExtension
  {
    try await self.getLbTrafficExtension(request: request, options: .init())
  }

  public func getLbTrafficExtension(
    request: GetLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.LbTrafficExtension {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getLbTrafficExtension(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkServicesV1.LbTrafficExtension {
    let request = GetLbTrafficExtensionRequest().with {
      $0.name = name
    }
    return try await self.getLbTrafficExtension(request: request)
  }

  public func createLbTrafficExtension(request: CreateLbTrafficExtensionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createLbTrafficExtension(request: request, options: .init())
  }

  public func createLbTrafficExtension(
    request: CreateLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createLbTrafficExtensionPollingUntilDone(request: CreateLbTrafficExtensionRequest)
    async throws -> any GoogleGax.PollableOperation<LbTrafficExtension>
  {
    try await self.createLbTrafficExtensionPollingUntilDone(request: request, options: .init())
  }

  public func createLbTrafficExtensionPollingUntilDone(
    request: CreateLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LbTrafficExtension> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<LbTrafficExtension>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createLbTrafficExtensionPollingUntilDone(
    parent: Swift.String,
    lbTrafficExtension: LbTrafficExtension?,
    lbTrafficExtensionId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<LbTrafficExtension> {
    let request = CreateLbTrafficExtensionRequest().with {
      $0.parent = parent
      $0.lbTrafficExtension = lbTrafficExtension
      $0.lbTrafficExtensionId = lbTrafficExtensionId
    }
    return try await self.createLbTrafficExtensionPollingUntilDone(request: request)
  }

  public func updateLbTrafficExtension(request: UpdateLbTrafficExtensionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateLbTrafficExtension(request: request, options: .init())
  }

  public func updateLbTrafficExtension(
    request: UpdateLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateLbTrafficExtensionPollingUntilDone(request: UpdateLbTrafficExtensionRequest)
    async throws -> any GoogleGax.PollableOperation<LbTrafficExtension>
  {
    try await self.updateLbTrafficExtensionPollingUntilDone(request: request, options: .init())
  }

  public func updateLbTrafficExtensionPollingUntilDone(
    request: UpdateLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LbTrafficExtension> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<LbTrafficExtension>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateLbTrafficExtensionPollingUntilDone(
    lbTrafficExtension: LbTrafficExtension?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<LbTrafficExtension> {
    let request = UpdateLbTrafficExtensionRequest().with {
      $0.lbTrafficExtension = lbTrafficExtension
      $0.updateMask = updateMask
    }
    return try await self.updateLbTrafficExtensionPollingUntilDone(request: request)
  }

  public func deleteLbTrafficExtension(request: DeleteLbTrafficExtensionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteLbTrafficExtension(request: request, options: .init())
  }

  public func deleteLbTrafficExtension(
    request: DeleteLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteLbTrafficExtensionPollingUntilDone(request: DeleteLbTrafficExtensionRequest)
    async throws -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteLbTrafficExtensionPollingUntilDone(request: request, options: .init())
  }

  public func deleteLbTrafficExtensionPollingUntilDone(
    request: DeleteLbTrafficExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteLbTrafficExtensionPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteLbTrafficExtensionRequest().with {
      $0.name = name
    }
    return try await self.deleteLbTrafficExtensionPollingUntilDone(request: request)
  }

  public func listLbRouteExtensions(request: ListLbRouteExtensionsRequest) async throws
    -> GoogleCloudNetworkServicesV1.ListLbRouteExtensionsResponse
  {
    try await self.listLbRouteExtensions(request: request, options: .init())
  }

  public func listLbRouteExtensions(
    request: ListLbRouteExtensionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.ListLbRouteExtensionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLbRouteExtensionsByItems(
    request: ListLbRouteExtensionsRequest
  ) -> any AsyncSequence<LbRouteExtension, Swift.Error> {
    self.listLbRouteExtensionsByItems(request: request, options: .init())
  }

  /// Lists `LbRouteExtension` resources in a given project and location.
  ///
  /// @Snippet(path: "DepService_ListLbRouteExtensions")
  public func listLbRouteExtensionsByItems(
    request: ListLbRouteExtensionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<LbRouteExtension, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudNetworkServicesV1.ListLbRouteExtensionsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLbRouteExtensions(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLbRouteExtensionsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<LbRouteExtension, Swift.Error> {
    let request = ListLbRouteExtensionsRequest().with {
      $0.parent = parent
    }
    return self.listLbRouteExtensionsByItems(request: request)
  }

  public func getLbRouteExtension(request: GetLbRouteExtensionRequest) async throws
    -> GoogleCloudNetworkServicesV1.LbRouteExtension
  {
    try await self.getLbRouteExtension(request: request, options: .init())
  }

  public func getLbRouteExtension(
    request: GetLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.LbRouteExtension {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getLbRouteExtension(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkServicesV1.LbRouteExtension {
    let request = GetLbRouteExtensionRequest().with {
      $0.name = name
    }
    return try await self.getLbRouteExtension(request: request)
  }

  public func createLbRouteExtension(request: CreateLbRouteExtensionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createLbRouteExtension(request: request, options: .init())
  }

  public func createLbRouteExtension(
    request: CreateLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createLbRouteExtensionPollingUntilDone(request: CreateLbRouteExtensionRequest)
    async throws -> any GoogleGax.PollableOperation<LbRouteExtension>
  {
    try await self.createLbRouteExtensionPollingUntilDone(request: request, options: .init())
  }

  public func createLbRouteExtensionPollingUntilDone(
    request: CreateLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LbRouteExtension> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<LbRouteExtension>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createLbRouteExtensionPollingUntilDone(
    parent: Swift.String,
    lbRouteExtension: LbRouteExtension?,
    lbRouteExtensionId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<LbRouteExtension> {
    let request = CreateLbRouteExtensionRequest().with {
      $0.parent = parent
      $0.lbRouteExtension = lbRouteExtension
      $0.lbRouteExtensionId = lbRouteExtensionId
    }
    return try await self.createLbRouteExtensionPollingUntilDone(request: request)
  }

  public func updateLbRouteExtension(request: UpdateLbRouteExtensionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateLbRouteExtension(request: request, options: .init())
  }

  public func updateLbRouteExtension(
    request: UpdateLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateLbRouteExtensionPollingUntilDone(request: UpdateLbRouteExtensionRequest)
    async throws -> any GoogleGax.PollableOperation<LbRouteExtension>
  {
    try await self.updateLbRouteExtensionPollingUntilDone(request: request, options: .init())
  }

  public func updateLbRouteExtensionPollingUntilDone(
    request: UpdateLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LbRouteExtension> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<LbRouteExtension>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateLbRouteExtensionPollingUntilDone(
    lbRouteExtension: LbRouteExtension?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<LbRouteExtension> {
    let request = UpdateLbRouteExtensionRequest().with {
      $0.lbRouteExtension = lbRouteExtension
      $0.updateMask = updateMask
    }
    return try await self.updateLbRouteExtensionPollingUntilDone(request: request)
  }

  public func deleteLbRouteExtension(request: DeleteLbRouteExtensionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteLbRouteExtension(request: request, options: .init())
  }

  public func deleteLbRouteExtension(
    request: DeleteLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteLbRouteExtensionPollingUntilDone(request: DeleteLbRouteExtensionRequest)
    async throws -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteLbRouteExtensionPollingUntilDone(request: request, options: .init())
  }

  public func deleteLbRouteExtensionPollingUntilDone(
    request: DeleteLbRouteExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteLbRouteExtensionPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteLbRouteExtensionRequest().with {
      $0.name = name
    }
    return try await self.deleteLbRouteExtensionPollingUntilDone(request: request)
  }

  public func listLbEdgeExtensions(request: ListLbEdgeExtensionsRequest) async throws
    -> GoogleCloudNetworkServicesV1.ListLbEdgeExtensionsResponse
  {
    try await self.listLbEdgeExtensions(request: request, options: .init())
  }

  public func listLbEdgeExtensions(
    request: ListLbEdgeExtensionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.ListLbEdgeExtensionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLbEdgeExtensionsByItems(
    request: ListLbEdgeExtensionsRequest
  ) -> any AsyncSequence<LbEdgeExtension, Swift.Error> {
    self.listLbEdgeExtensionsByItems(request: request, options: .init())
  }

  /// Lists `LbEdgeExtension` resources in a given project and location.
  ///
  /// @Snippet(path: "DepService_ListLbEdgeExtensions")
  public func listLbEdgeExtensionsByItems(
    request: ListLbEdgeExtensionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<LbEdgeExtension, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudNetworkServicesV1.ListLbEdgeExtensionsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLbEdgeExtensions(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLbEdgeExtensionsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<LbEdgeExtension, Swift.Error> {
    let request = ListLbEdgeExtensionsRequest().with {
      $0.parent = parent
    }
    return self.listLbEdgeExtensionsByItems(request: request)
  }

  public func getLbEdgeExtension(request: GetLbEdgeExtensionRequest) async throws
    -> GoogleCloudNetworkServicesV1.LbEdgeExtension
  {
    try await self.getLbEdgeExtension(request: request, options: .init())
  }

  public func getLbEdgeExtension(
    request: GetLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.LbEdgeExtension {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getLbEdgeExtension(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkServicesV1.LbEdgeExtension {
    let request = GetLbEdgeExtensionRequest().with {
      $0.name = name
    }
    return try await self.getLbEdgeExtension(request: request)
  }

  public func createLbEdgeExtension(request: CreateLbEdgeExtensionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createLbEdgeExtension(request: request, options: .init())
  }

  public func createLbEdgeExtension(
    request: CreateLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createLbEdgeExtensionPollingUntilDone(request: CreateLbEdgeExtensionRequest)
    async throws -> any GoogleGax.PollableOperation<LbEdgeExtension>
  {
    try await self.createLbEdgeExtensionPollingUntilDone(request: request, options: .init())
  }

  public func createLbEdgeExtensionPollingUntilDone(
    request: CreateLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LbEdgeExtension> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<LbEdgeExtension>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createLbEdgeExtensionPollingUntilDone(
    parent: Swift.String,
    lbEdgeExtension: LbEdgeExtension?,
    lbEdgeExtensionId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<LbEdgeExtension> {
    let request = CreateLbEdgeExtensionRequest().with {
      $0.parent = parent
      $0.lbEdgeExtension = lbEdgeExtension
      $0.lbEdgeExtensionId = lbEdgeExtensionId
    }
    return try await self.createLbEdgeExtensionPollingUntilDone(request: request)
  }

  public func updateLbEdgeExtension(request: UpdateLbEdgeExtensionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateLbEdgeExtension(request: request, options: .init())
  }

  public func updateLbEdgeExtension(
    request: UpdateLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateLbEdgeExtensionPollingUntilDone(request: UpdateLbEdgeExtensionRequest)
    async throws -> any GoogleGax.PollableOperation<LbEdgeExtension>
  {
    try await self.updateLbEdgeExtensionPollingUntilDone(request: request, options: .init())
  }

  public func updateLbEdgeExtensionPollingUntilDone(
    request: UpdateLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LbEdgeExtension> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<LbEdgeExtension>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateLbEdgeExtensionPollingUntilDone(
    lbEdgeExtension: LbEdgeExtension?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<LbEdgeExtension> {
    let request = UpdateLbEdgeExtensionRequest().with {
      $0.lbEdgeExtension = lbEdgeExtension
      $0.updateMask = updateMask
    }
    return try await self.updateLbEdgeExtensionPollingUntilDone(request: request)
  }

  public func deleteLbEdgeExtension(request: DeleteLbEdgeExtensionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteLbEdgeExtension(request: request, options: .init())
  }

  public func deleteLbEdgeExtension(
    request: DeleteLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteLbEdgeExtensionPollingUntilDone(request: DeleteLbEdgeExtensionRequest)
    async throws -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteLbEdgeExtensionPollingUntilDone(request: request, options: .init())
  }

  public func deleteLbEdgeExtensionPollingUntilDone(
    request: DeleteLbEdgeExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteLbEdgeExtensionPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteLbEdgeExtensionRequest().with {
      $0.name = name
    }
    return try await self.deleteLbEdgeExtensionPollingUntilDone(request: request)
  }

  public func listAuthzExtensions(request: ListAuthzExtensionsRequest) async throws
    -> GoogleCloudNetworkServicesV1.ListAuthzExtensionsResponse
  {
    try await self.listAuthzExtensions(request: request, options: .init())
  }

  public func listAuthzExtensions(
    request: ListAuthzExtensionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.ListAuthzExtensionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAuthzExtensionsByItems(
    request: ListAuthzExtensionsRequest
  ) -> any AsyncSequence<AuthzExtension, Swift.Error> {
    self.listAuthzExtensionsByItems(request: request, options: .init())
  }

  /// Lists `AuthzExtension` resources in a given project and location.
  ///
  /// @Snippet(path: "DepService_ListAuthzExtensions")
  public func listAuthzExtensionsByItems(
    request: ListAuthzExtensionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<AuthzExtension, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudNetworkServicesV1.ListAuthzExtensionsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listAuthzExtensions(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAuthzExtensionsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<AuthzExtension, Swift.Error> {
    let request = ListAuthzExtensionsRequest().with {
      $0.parent = parent
    }
    return self.listAuthzExtensionsByItems(request: request)
  }

  public func getAuthzExtension(request: GetAuthzExtensionRequest) async throws
    -> GoogleCloudNetworkServicesV1.AuthzExtension
  {
    try await self.getAuthzExtension(request: request, options: .init())
  }

  public func getAuthzExtension(
    request: GetAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkServicesV1.AuthzExtension {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAuthzExtension(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkServicesV1.AuthzExtension {
    let request = GetAuthzExtensionRequest().with {
      $0.name = name
    }
    return try await self.getAuthzExtension(request: request)
  }

  public func createAuthzExtension(request: CreateAuthzExtensionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAuthzExtension(request: request, options: .init())
  }

  public func createAuthzExtension(
    request: CreateAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAuthzExtensionPollingUntilDone(request: CreateAuthzExtensionRequest)
    async throws -> any GoogleGax.PollableOperation<AuthzExtension>
  {
    try await self.createAuthzExtensionPollingUntilDone(request: request, options: .init())
  }

  public func createAuthzExtensionPollingUntilDone(
    request: CreateAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AuthzExtension> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AuthzExtension>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAuthzExtensionPollingUntilDone(
    parent: Swift.String,
    authzExtension: AuthzExtension?,
    authzExtensionId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<AuthzExtension> {
    let request = CreateAuthzExtensionRequest().with {
      $0.parent = parent
      $0.authzExtension = authzExtension
      $0.authzExtensionId = authzExtensionId
    }
    return try await self.createAuthzExtensionPollingUntilDone(request: request)
  }

  public func updateAuthzExtension(request: UpdateAuthzExtensionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAuthzExtension(request: request, options: .init())
  }

  public func updateAuthzExtension(
    request: UpdateAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAuthzExtensionPollingUntilDone(request: UpdateAuthzExtensionRequest)
    async throws -> any GoogleGax.PollableOperation<AuthzExtension>
  {
    try await self.updateAuthzExtensionPollingUntilDone(request: request, options: .init())
  }

  public func updateAuthzExtensionPollingUntilDone(
    request: UpdateAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AuthzExtension> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AuthzExtension>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateAuthzExtensionPollingUntilDone(
    authzExtension: AuthzExtension?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<AuthzExtension> {
    let request = UpdateAuthzExtensionRequest().with {
      $0.authzExtension = authzExtension
      $0.updateMask = updateMask
    }
    return try await self.updateAuthzExtensionPollingUntilDone(request: request)
  }

  public func deleteAuthzExtension(request: DeleteAuthzExtensionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAuthzExtension(request: request, options: .init())
  }

  public func deleteAuthzExtension(
    request: DeleteAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAuthzExtensionPollingUntilDone(request: DeleteAuthzExtensionRequest)
    async throws -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAuthzExtensionPollingUntilDone(request: request, options: .init())
  }

  public func deleteAuthzExtensionPollingUntilDone(
    request: DeleteAuthzExtensionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAuthzExtensionPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteAuthzExtensionRequest().with {
      $0.name = name
    }
    return try await self.deleteAuthzExtensionPollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "DepService_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DepService_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
