// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// EndpointPolicy is a resource that helps apply desired configuration
/// on the endpoints that match specific criteria.
/// For example, this resource can be used to apply "authentication config"
/// an all endpoints that serve on port 8080.
public struct EndpointPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of the EndpointPolicy resource. It matches pattern
  /// `projects/{project}/locations/*/endpointPolicies/{endpoint_policy}`.
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp when the resource was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The timestamp when the resource was updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Optional. Set of label tags associated with the EndpointPolicy resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. The type of endpoint policy. This is primarily used to validate
  /// the configuration.
  public var type: EndpointPolicy.EndpointPolicyType = EndpointPolicy.EndpointPolicyType()

  /// Optional. This field specifies the URL of AuthorizationPolicy resource that
  /// applies authorization policies to the inbound traffic at the
  /// matched endpoints. Refer to Authorization. If this field is not
  /// specified, authorization is disabled(no authz checks) for this
  /// endpoint.
  public var authorizationPolicy: Swift.String = Swift.String()

  /// Required. A matcher that selects endpoints to which the policies should be
  /// applied.
  public var endpointMatcher: EndpointMatcher? = nil

  /// Optional. Port selector for the (matched) endpoints. If no port selector is
  /// provided, the matched config is applied to all ports.
  public var trafficPortSelector: TrafficPortSelector? = nil

  /// Optional. A free-text description of the resource. Max length 1024
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Optional. A URL referring to ServerTlsPolicy resource. ServerTlsPolicy is
  /// used to determine the authentication policy to be applied to terminate the
  /// inbound traffic at the identified backends. If this field is not set,
  /// authentication is disabled(open) for this endpoint.
  public var serverTlsPolicy: Swift.String = Swift.String()

  /// Optional. Deprecated: This field is not used and is a no-op.
  /// A URL referring to a ClientTlsPolicy resource. ClientTlsPolicy can be set
  /// to specify the authentication for traffic from the proxy to the actual
  /// endpoints. More specifically, it is applied to the outgoing traffic from
  /// the proxy to the endpoint. This is typically used for sidecar model where
  /// the proxy identifies itself as endpoint to the control plane, with the
  /// connection between sidecar and endpoint requiring authentication. If this
  /// field is not set, authentication is disabled(open). Applicable only when
  /// EndpointPolicyType is SIDECAR_PROXY.
  @available(*, deprecated)
  public var clientTlsPolicy: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EndpointPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EndpointPolicy().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let type = CodingKeys(stringValue: "type")
    static let authorizationPolicy = CodingKeys(stringValue: "authorizationPolicy")
    static let endpointMatcher = CodingKeys(stringValue: "endpointMatcher")
    static let trafficPortSelector = CodingKeys(stringValue: "trafficPortSelector")
    static let description = CodingKeys(stringValue: "description")
    static let serverTlsPolicy = CodingKeys(stringValue: "serverTlsPolicy")
    static let clientTlsPolicy = CodingKeys(stringValue: "clientTlsPolicy")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "type",
      "authorizationPolicy",
      "endpointMatcher",
      "trafficPortSelector",
      "description",
      "serverTlsPolicy",
      "clientTlsPolicy",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      EndpointPolicy.EndpointPolicyType.self, forKey: .type)
    {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .authorizationPolicy) {
      self.authorizationPolicy = value
    }
    self.endpointMatcher = try container.decodeIfPresent(
      EndpointMatcher.self, forKey: .endpointMatcher)
    self.trafficPortSelector = try container.decodeIfPresent(
      TrafficPortSelector.self, forKey: .trafficPortSelector)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serverTlsPolicy) {
      self.serverTlsPolicy = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientTlsPolicy) {
      self.clientTlsPolicy = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.authorizationPolicy, forKey: .authorizationPolicy)
    try container.encodeIfPresent(self.endpointMatcher, forKey: .endpointMatcher)
    try container.encodeIfPresent(self.trafficPortSelector, forKey: .trafficPortSelector)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.serverTlsPolicy, forKey: .serverTlsPolicy)
    try container.encode(self.clientTlsPolicy, forKey: .clientTlsPolicy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type of endpoint policy.
  public enum EndpointPolicyType: Codable, Equatable, Sendable {
    /// Default value. Must not be used.
    case unspecified
    /// Represents a proxy deployed as a sidecar.
    case sidecarProxy
    /// Represents a proxyless gRPC backend.
    case grpcServer
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .sidecarProxy: return 1
      case .grpcServer: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ENDPOINT_POLICY_TYPE_UNSPECIFIED"
      case .sidecarProxy: return "SIDECAR_PROXY"
      case .grpcServer: return "GRPC_SERVER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EndpointPolicyType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ENDPOINT_POLICY_TYPE_UNSPECIFIED": self = .unspecified
      case "SIDECAR_PROXY": self = .sidecarProxy
      case "GRPC_SERVER": self = .grpcServer
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EndpointPolicyType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .sidecarProxy
      case 2: self = .grpcServer
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ENDPOINT_POLICY_TYPE_UNSPECIFIED")
      case .sidecarProxy: return try container.encode("SIDECAR_PROXY")
      case .grpcServer: return try container.encode("GRPC_SERVER")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkservices.v1.EndpointPolicy"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
