// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Gateway represents the configuration for a proxy, typically a load balancer.
/// It captures the ip:port over which the services are exposed by the proxy,
/// along with any policy configurations. Routes have reference to to Gateways to
/// dictate how requests should be routed by this Gateway.
public struct Gateway: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of the Gateway resource. It matches pattern
  /// `projects/*/locations/*/gateways/<gateway_name>`.
  public var name: Swift.String = Swift.String()

  /// Output only. Server-defined URL of this resource
  public var selfLink: Swift.String = Swift.String()

  /// Output only. The timestamp when the resource was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The timestamp when the resource was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Set of label tags associated with the Gateway resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. A free-text description of the resource. Max length 1024
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Immutable. The type of the customer managed gateway.
  /// This field is required. If unspecified, an error is returned.
  public var type: Gateway.Type_ = Gateway.Type_()

  /// Optional. Zero or one IPv4 or IPv6 address on which the Gateway will
  /// receive the traffic. When no address is provided, an IP from the subnetwork
  /// is allocated
  ///
  /// This field only applies to gateways of type 'SECURE_WEB_GATEWAY'.
  /// Gateways of type 'OPEN_MESH' listen on 0.0.0.0 for IPv4 and :: for IPv6.
  public var addresses: [Swift.String] = []

  /// Required. One or more port numbers (1-65535), on which the Gateway will
  /// receive traffic. The proxy binds to the specified ports.
  /// Gateways of type 'SECURE_WEB_GATEWAY' are limited to 5 ports.
  /// Gateways of type 'OPEN_MESH' listen on 0.0.0.0 for IPv4 and :: for IPv6 and
  /// support multiple ports.
  public var ports: [Swift.Int32] = []

  /// Optional. If true, the Gateway will listen on all ports. This is mutually
  /// exclusive with the `ports` field. This field only applies to gateways of
  /// type 'SECURE_WEB_GATEWAY'.
  public var allPorts: Swift.Bool = Swift.Bool()

  /// Optional. Scope determines how configuration across multiple Gateway
  /// instances are merged. The configuration for multiple Gateway instances with
  /// the same scope will be merged as presented as a single configuration to the
  /// proxy/load balancer.
  ///
  /// Max length 64 characters.
  /// Scope should start with a letter and can only have letters, numbers,
  /// hyphens.
  public var scope: Swift.String = Swift.String()

  /// Optional. A fully-qualified ServerTLSPolicy URL reference. Specifies how
  /// TLS traffic is terminated. If empty, TLS termination is disabled.
  public var serverTlsPolicy: Swift.String = Swift.String()

  /// Optional. A fully-qualified Certificates URL reference. The proxy presents
  /// a Certificate (selected based on SNI) when establishing a TLS connection.
  /// This feature only applies to gateways of type 'SECURE_WEB_GATEWAY'.
  public var certificateUrls: [Swift.String] = []

  /// Optional. A fully-qualified GatewaySecurityPolicy URL reference.
  /// Defines how a server should apply security policy to inbound
  /// (VM to Proxy) initiated connections.
  ///
  /// For example:
  /// `projects/*/locations/*/gatewaySecurityPolicies/swg-policy`.
  ///
  /// This policy is specific to gateways of type 'SECURE_WEB_GATEWAY'.
  public var gatewaySecurityPolicy: Swift.String = Swift.String()

  /// Optional. The relative resource name identifying the VPC network that is
  /// using this configuration. For example:
  /// `projects/*/global/networks/network-1`.
  ///
  /// Currently, this field is specific to gateways of type 'SECURE_WEB_GATEWAY'.
  public var network: Swift.String = Swift.String()

  /// Optional. The relative resource name identifying  the subnetwork in which
  /// this SWG is allocated. For example:
  /// `projects/*/regions/us-central1/subnetworks/network-1`
  ///
  /// Currently, this field is specific to gateways of type 'SECURE_WEB_GATEWAY".
  public var subnetwork: Swift.String = Swift.String()

  /// Optional. The IP Version that will be used by this gateway. Valid options
  /// are IPV4 or IPV6. Default is IPV4.
  public var ipVersion: Gateway.IpVersion = Gateway.IpVersion()

  /// Optional. Determines if envoy will insert internal debug headers into
  /// upstream requests. Other Envoy headers may still be injected. By default,
  /// envoy will not insert any debug headers.
  public var envoyHeaders: EnvoyHeaders? = nil

  /// Optional. The routing mode of the Gateway.
  /// This field is configurable only for gateways of type SECURE_WEB_GATEWAY.
  /// This field is required for gateways of type SECURE_WEB_GATEWAY.
  public var routingMode: Gateway.RoutingMode = Gateway.RoutingMode()

  /// Optional. If true, the gateway will allow traffic from clients outside of
  /// the region where the gateway is located.
  /// This field is configurable only for gateways of type SECURE_WEB_GATEWAY.
  public var allowGlobalAccess: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Gateway`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Gateway().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The type of the customer-managed gateway.
  /// Possible values are:
  /// * OPEN_MESH
  /// * SECURE_WEB_GATEWAY
  public enum Type_: Codable, Equatable, Sendable {
    /// The type of the customer managed gateway is unspecified.
    case unspecified
    /// The type of the customer managed gateway is TrafficDirector Open
    /// Mesh.
    case openMesh
    /// The type of the customer managed gateway is SecureWebGateway (SWG).
    case secureWebGateway
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .openMesh: return 1
      case .secureWebGateway: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .openMesh: return "OPEN_MESH"
      case .secureWebGateway: return "SECURE_WEB_GATEWAY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "OPEN_MESH": self = .openMesh
      case "SECURE_WEB_GATEWAY": self = .secureWebGateway
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .openMesh
      case 2: self = .secureWebGateway
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .openMesh: return try container.encode(1)
      case .secureWebGateway: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The types of IP version for the gateway.
  /// Possible values are:
  /// * IPV4
  /// * IPV6
  public enum IpVersion: Codable, Equatable, Sendable {
    /// The type when IP version is not specified. Defaults to IPV4.
    case unspecified
    /// The type for IP version 4.
    case ipv4
    /// The type for IP version 6.
    case ipv6
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ipv4: return 1
      case .ipv6: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "IP_VERSION_UNSPECIFIED"
      case .ipv4: return "IPV4"
      case .ipv6: return "IPV6"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:IpVersion/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "IP_VERSION_UNSPECIFIED": self = .unspecified
      case "IPV4": self = .ipv4
      case "IPV6": self = .ipv6
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:IpVersion/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ipv4
      case 2: self = .ipv6
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ipv4: return try container.encode(1)
      case .ipv6: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The routing mode of the Gateway, to determine how the Gateway routes
  /// traffic. Today, this field only applies to Gateways of type
  /// SECURE_WEB_GATEWAY. Possible values are:
  /// * EXPLICIT_ROUTING_MODE
  /// * NEXT_HOP_ROUTING_MODE
  public enum RoutingMode: Codable, Equatable, Sendable {
    /// The routing mode is explicit; clients are configured to send
    /// traffic through the gateway. This is the default routing mode.
    case explicitRoutingMode
    /// The routing mode is next-hop. Clients are unaware of the gateway,
    /// and a route (advanced route or other route type)
    /// can be configured to direct traffic from client to gateway.
    /// The gateway then acts as a next-hop to the destination.
    case nextHopRoutingMode
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .explicitRoutingMode
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .explicitRoutingMode: return 0
      case .nextHopRoutingMode: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .explicitRoutingMode: return "EXPLICIT_ROUTING_MODE"
      case .nextHopRoutingMode: return "NEXT_HOP_ROUTING_MODE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RoutingMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EXPLICIT_ROUTING_MODE": self = .explicitRoutingMode
      case "NEXT_HOP_ROUTING_MODE": self = .nextHopRoutingMode
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RoutingMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .explicitRoutingMode
      case 1: self = .nextHopRoutingMode
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .explicitRoutingMode: return try container.encode(0)
      case .nextHopRoutingMode: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkservices.v1.Gateway"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
