// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request used with the `ListWasmPlugins` method.
public struct ListWasmPluginsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project and location from which the `WasmPlugin` resources
  /// are listed, specified in the following format:
  /// `projects/{project}/locations/global`.
  public var parent: Swift.String = Swift.String()

  /// Maximum number of `WasmPlugin` resources to return per call.
  /// If not specified, at most 50 `WasmPlugin` resources are returned.
  /// The maximum value is 1000; values above 1000 are coerced to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The value returned by the last `ListWasmPluginsResponse` call.
  /// Indicates that this is a continuation of a prior
  /// `ListWasmPlugins` call, and that the
  /// next page of data is to be returned.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListWasmPluginsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListWasmPluginsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkservices.v1.ListWasmPluginsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
