// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Mesh represents a logical configuration grouping for workload to workload
/// communication within a service mesh. Routes that point to mesh dictate how
/// requests are routed within this logical mesh boundary.
public struct Mesh: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Name of the Mesh resource. It matches pattern
  /// `projects/*/locations/*/meshes/<mesh_name>`.
  public var name: Swift.String = Swift.String()

  /// Output only. Server-defined URL of this resource
  public var selfLink: Swift.String = Swift.String()

  /// Output only. The timestamp when the resource was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp when the resource was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Set of label tags associated with the Mesh resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. A free-text description of the resource. Max length 1024
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Optional. If set to a valid TCP port (1-65535), instructs the SIDECAR proxy
  /// to listen on the specified port of localhost (127.0.0.1) address. The
  /// SIDECAR proxy will expect all traffic to be redirected to this port
  /// regardless of its actual ip:port destination. If unset, a port '15001' is
  /// used as the interception port. This is applicable only for sidecar proxy
  /// deployments.
  public var interceptionPort: Swift.Int32 = Swift.Int32()

  /// Optional. Determines if envoy will insert internal debug headers into
  /// upstream requests. Other Envoy headers may still be injected. By default,
  /// envoy will not insert any debug headers.
  public var envoyHeaders: EnvoyHeaders? = nil

  /// Initialize a new instance of `Mesh`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Mesh().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkservices.v1.Mesh"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
