// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol NetworkServicesStub {
    func listEndpointPolicies(
      request: ListEndpointPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListEndpointPoliciesResponse

    func getEndpointPolicy(
      request: GetEndpointPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.EndpointPolicy

    func createEndpointPolicy(
      request: CreateEndpointPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateEndpointPolicy(
      request: UpdateEndpointPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteEndpointPolicy(
      request: DeleteEndpointPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listWasmPluginVersions(
      request: ListWasmPluginVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListWasmPluginVersionsResponse

    func getWasmPluginVersion(
      request: GetWasmPluginVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.WasmPluginVersion

    func createWasmPluginVersion(
      request: CreateWasmPluginVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteWasmPluginVersion(
      request: DeleteWasmPluginVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listWasmPlugins(
      request: ListWasmPluginsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListWasmPluginsResponse

    func getWasmPlugin(
      request: GetWasmPluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.WasmPlugin

    func createWasmPlugin(
      request: CreateWasmPluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateWasmPlugin(
      request: UpdateWasmPluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteWasmPlugin(
      request: DeleteWasmPluginRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listGateways(
      request: ListGatewaysRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListGatewaysResponse

    func getGateway(
      request: GetGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.Gateway

    func createGateway(
      request: CreateGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateGateway(
      request: UpdateGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteGateway(
      request: DeleteGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listGrpcRoutes(
      request: ListGrpcRoutesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListGrpcRoutesResponse

    func getGrpcRoute(
      request: GetGrpcRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.GrpcRoute

    func createGrpcRoute(
      request: CreateGrpcRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateGrpcRoute(
      request: UpdateGrpcRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteGrpcRoute(
      request: DeleteGrpcRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listHttpRoutes(
      request: ListHttpRoutesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListHttpRoutesResponse

    func getHttpRoute(
      request: GetHttpRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.HttpRoute

    func createHttpRoute(
      request: CreateHttpRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateHttpRoute(
      request: UpdateHttpRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteHttpRoute(
      request: DeleteHttpRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listTcpRoutes(
      request: ListTcpRoutesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListTcpRoutesResponse

    func getTcpRoute(
      request: GetTcpRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.TcpRoute

    func createTcpRoute(
      request: CreateTcpRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateTcpRoute(
      request: UpdateTcpRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteTcpRoute(
      request: DeleteTcpRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listTlsRoutes(
      request: ListTlsRoutesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListTlsRoutesResponse

    func getTlsRoute(
      request: GetTlsRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.TlsRoute

    func createTlsRoute(
      request: CreateTlsRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateTlsRoute(
      request: UpdateTlsRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteTlsRoute(
      request: DeleteTlsRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listServiceBindings(
      request: ListServiceBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListServiceBindingsResponse

    func getServiceBinding(
      request: GetServiceBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ServiceBinding

    func createServiceBinding(
      request: CreateServiceBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateServiceBinding(
      request: UpdateServiceBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteServiceBinding(
      request: DeleteServiceBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listMeshes(
      request: ListMeshesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListMeshesResponse

    func getMesh(
      request: GetMeshRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.Mesh

    func createMesh(
      request: CreateMeshRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateMesh(
      request: UpdateMeshRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteMesh(
      request: DeleteMeshRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listServiceLbPolicies(
      request: ListServiceLbPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListServiceLbPoliciesResponse

    func getServiceLbPolicy(
      request: GetServiceLbPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ServiceLbPolicy

    func createServiceLbPolicy(
      request: CreateServiceLbPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateServiceLbPolicy(
      request: UpdateServiceLbPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteServiceLbPolicy(
      request: DeleteServiceLbPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getGatewayRouteView(
      request: GetGatewayRouteViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.GatewayRouteView

    func getMeshRouteView(
      request: GetMeshRouteViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.MeshRouteView

    func listGatewayRouteViews(
      request: ListGatewayRouteViewsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListGatewayRouteViewsResponse

    func listMeshRouteViews(
      request: ListMeshRouteViewsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListMeshRouteViewsResponse

    func listAgentGateways(
      request: ListAgentGatewaysRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.ListAgentGatewaysResponse

    func getAgentGateway(
      request: GetAgentGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkServicesV1.AgentGateway

    func createAgentGateway(
      request: CreateAgentGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateAgentGateway(
      request: UpdateAgentGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteAgentGateway(
      request: DeleteAgentGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
