// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// TlsRoute defines how traffic should be routed based on SNI and other matching
/// L3 attributes.
public struct TlsRoute: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of the TlsRoute resource. It matches pattern
  /// `projects/*/locations/*/tlsRoutes/tls_route_name>`.
  public var name: Swift.String = Swift.String()

  /// Output only. Server-defined URL of this resource
  public var selfLink: Swift.String = Swift.String()

  /// Output only. The timestamp when the resource was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The timestamp when the resource was updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Optional. A free-text description of the resource. Max length 1024
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Required. Rules that define how traffic is routed and handled. At least one
  /// RouteRule must be supplied. If there are multiple rules then the action
  /// taken will be the first rule to match.
  public var rules: [TlsRoute.RouteRule] = []

  /// Optional. Meshes defines a list of meshes this TlsRoute is attached to, as
  /// one of the routing rules to route the requests served by the mesh.
  ///
  /// Each mesh reference should match the pattern:
  /// `projects/*/locations/*/meshes/<mesh_name>`
  ///
  /// The attached Mesh should be of a type SIDECAR
  public var meshes: [Swift.String] = []

  /// Optional. Gateways defines a list of gateways this TlsRoute is attached to,
  /// as one of the routing rules to route the requests served by the gateway.
  ///
  /// Each gateway reference should match the pattern:
  /// `projects/*/locations/*/gateways/<gateway_name>`
  public var gateways: [Swift.String] = []

  /// Optional. TargetProxies defines a list of TargetTcpProxies this TlsRoute is
  /// attached to, as one of the routing rules to route the requests served by
  /// the TargetTcpProxy.
  ///
  /// Each TargetTcpProxy reference should match the pattern:
  /// `projects/*/locations/*/targetTcpProxies/<target_tcp_proxy_name>`
  public var targetProxies: [Swift.String] = []

  /// Optional. Set of label tags associated with the TlsRoute resource.
  public var labels: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TlsRoute`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TlsRoute().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let selfLink = CodingKeys(stringValue: "selfLink")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let description = CodingKeys(stringValue: "description")
    static let rules = CodingKeys(stringValue: "rules")
    static let meshes = CodingKeys(stringValue: "meshes")
    static let gateways = CodingKeys(stringValue: "gateways")
    static let targetProxies = CodingKeys(stringValue: "targetProxies")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "selfLink",
      "createTime",
      "updateTime",
      "description",
      "rules",
      "meshes",
      "gateways",
      "targetProxies",
      "labels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .selfLink) {
      self.selfLink = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([TlsRoute.RouteRule].self, forKey: .rules) {
      self.rules = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .meshes) {
      self.meshes = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .gateways) {
      self.gateways = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .targetProxies) {
      self.targetProxies = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.selfLink, forKey: .selfLink)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.rules, forKey: .rules)
    try container.encode(self.meshes, forKey: .meshes)
    try container.encode(self.gateways, forKey: .gateways)
    try container.encode(self.targetProxies, forKey: .targetProxies)
    try container.encode(self.labels, forKey: .labels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Specifies how to match traffic and how to route traffic when traffic is
  /// matched.
  public struct RouteRule: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. RouteMatch defines the predicate used to match requests to a
    /// given action. Multiple match types are "OR"ed for evaluation. Atleast one
    /// RouteMatch must be supplied.
    public var matches: [TlsRoute.RouteMatch] = []

    /// Required. The detailed rule defining how to route matched traffic.
    public var action: TlsRoute.RouteAction? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RouteRule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RouteRule().with { $0.matches = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let matches = CodingKeys(stringValue: "matches")
      static let action = CodingKeys(stringValue: "action")

      static let _knownKeys: Set<Swift.String> = [
        "matches",
        "action",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([TlsRoute.RouteMatch].self, forKey: .matches) {
        self.matches = value
      }
      self.action = try container.decodeIfPresent(TlsRoute.RouteAction.self, forKey: .action)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.matches, forKey: .matches)
      try container.encodeIfPresent(self.action, forKey: .action)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.networkservices.v1.TlsRoute.RouteRule"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// RouteMatch defines the predicate used to match requests to a given action.
  /// Multiple match types are "AND"ed for evaluation.
  public struct RouteMatch: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. SNI (server name indicator) to match against.
    /// SNI will be matched against all wildcard domains, i.e. `www.example.com`
    /// will be first matched against `www.example.com`, then `*.example.com`,
    /// then `*.com.`
    /// Partial wildcards are not supported, and values like *w.example.com are
    /// invalid.
    /// At least one of sni_host and alpn is required.
    /// Up to 100 sni hosts across all matches can be set.
    public var sniHost: [Swift.String] = []

    /// Optional. ALPN (Application-Layer Protocol Negotiation) to match against.
    /// Examples: "http/1.1", "h2".
    /// At least one of sni_host and alpn is required.
    /// Up to 5 alpns across all matches can be set.
    public var alpn: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RouteMatch`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RouteMatch().with { $0.sniHost = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sniHost = CodingKeys(stringValue: "sniHost")
      static let alpn = CodingKeys(stringValue: "alpn")

      static let _knownKeys: Set<Swift.String> = [
        "sniHost",
        "alpn",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .sniHost) {
        self.sniHost = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .alpn) {
        self.alpn = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sniHost, forKey: .sniHost)
      try container.encode(self.alpn, forKey: .alpn)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.networkservices.v1.TlsRoute.RouteMatch"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The specifications for routing traffic and applying associated policies.
  public struct RouteAction: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The destination services to which traffic should be forwarded.
    /// At least one destination service is required.
    public var destinations: [TlsRoute.RouteDestination] = []

    /// Optional. Specifies the idle timeout for the selected route. The idle
    /// timeout is defined as the period in which there are no bytes sent or
    /// received on either the upstream or downstream connection. If not set, the
    /// default idle timeout is 1 hour. If set to 0s, the timeout will be
    /// disabled.
    public var idleTimeout: GoogleWKT.Duration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RouteAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RouteAction().with { $0.destinations = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let destinations = CodingKeys(stringValue: "destinations")
      static let idleTimeout = CodingKeys(stringValue: "idleTimeout")

      static let _knownKeys: Set<Swift.String> = [
        "destinations",
        "idleTimeout",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [TlsRoute.RouteDestination].self, forKey: .destinations)
      {
        self.destinations = value
      }
      self.idleTimeout = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .idleTimeout)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.destinations, forKey: .destinations)
      try container.encodeIfPresent(self.idleTimeout, forKey: .idleTimeout)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.networkservices.v1.TlsRoute.RouteAction"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Describe the destination for traffic to be routed to.
  public struct RouteDestination: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The URL of a BackendService to route traffic to.
    public var serviceName: Swift.String = Swift.String()

    /// Optional. Specifies the proportion of requests forwarded to the backend
    /// referenced by the service_name field. This is computed as:
    /// - weight/Sum(weights in destinations)
    /// Weights in all destinations does not need to sum up to 100.
    public var weight: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RouteDestination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RouteDestination().with { $0.serviceName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let serviceName = CodingKeys(stringValue: "serviceName")
      static let weight = CodingKeys(stringValue: "weight")

      static let _knownKeys: Set<Swift.String> = [
        "serviceName",
        "weight",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceName) {
        self.serviceName = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .weight) {
        self.weight = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.serviceName, forKey: .serviceName)
      try container.encode(self.weight, forKey: .weight)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.networkservices.v1.TlsRoute.RouteDestination"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkservices.v1.TlsRoute"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
