// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request used by the `UpdateWasmPlugin` method.
public struct UpdateWasmPluginRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Used to specify the fields to be overwritten in the
  /// `WasmPlugin` resource by the update.
  /// The fields specified in the `update_mask` field are relative to the
  /// resource, not the full request.
  /// An omitted `update_mask` field is treated as an implied `update_mask`
  /// field equivalent to all fields that are populated (that have a non-empty
  /// value).
  /// The `update_mask` field supports a special value `*`, which means that
  /// each field in the given `WasmPlugin` resource (including the empty ones)
  /// replaces the current value.
  public var updateMask: GoogleWKT.WKTFieldMask? = nil

  /// Required. Updated `WasmPlugin` resource.
  public var wasmPlugin: WasmPlugin? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateWasmPluginRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateWasmPluginRequest().with { $0.updateMask = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let wasmPlugin = CodingKeys(stringValue: "wasmPlugin")

    static let _knownKeys: Set<Swift.String> = [
      "updateMask",
      "wasmPlugin",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.updateMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .updateMask)
    self.wasmPlugin = try container.decodeIfPresent(WasmPlugin.self, forKey: .wasmPlugin)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encodeIfPresent(self.wasmPlugin, forKey: .wasmPlugin)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `UpdateWasmPluginRequest`: `"type.googleapis.com/google.cloud.networkservices.v1.UpdateWasmPluginRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkservices.v1.UpdateWasmPluginRequest"
  }

  /// Initialize an instance of `UpdateWasmPluginRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.networkservices.v1.UpdateWasmPluginRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `UpdateWasmPluginRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
